### ISSUE TITLE
Cannot use @Valid on @Transient properties [DATAREST-1005]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#1368]
**[Craig](https://jira.spring.io/secure/ViewProfile.jspa?name=candrews)** opened **[DATAREST-1005](https://jira.spring.io/browse/DATAREST-1005?redirect=false)** and commented

An entity class like this:

```java
public class Person {
  @javax.persistence.Transient
  @javax.validation.constraints.NotNull
  private String temporary;

  @javax.validation.constraints.NotNull
  private String firstName;
}
```

Will result in an error when validated by Spring Data REST:

```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: JSR-303 validated property 'person.temporary' does not have a corresponding accessor for Spring data binding - check your DataBinder's configuration (bean property versus direct field access)
	at org.springframework.data.rest.core.ValidationErrors$1.getPropertyValue(ValidationErrors.java:90)
	at org.springframework.validation.AbstractPropertyBindingResult.getActualFieldValue(AbstractPropertyBindingResult.java:99)
	at org.springframework.validation.AbstractBindingResult.getRawFieldValue(AbstractBindingResult.java:283)
	at org.springframework.validation.beanvalidation.SpringValidatorAdapter.getRejectedValue(SpringValidatorAdapter.java:260)
	at org.springframework.validation.beanvalidation.SpringValidatorAdapter.processConstraintViolations(SpringValidatorAdapter.java:140)
	at org.springframework.validation.beanvalidation.SpringValidatorAdapter.validate(SpringValidatorAdapter.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

The problem is that the getters/setters for the transient field aren't in the persistent entity metamodel (see [DATACMNS-978](https://jira.spring.io/browse/DATACMNS-978)) so they're not found when validation tries to use them at https://github.com/spring-projects/spring-data-rest/blob/2.6.0.RELEASE/spring-data-rest-core/src/main/java/org/springframework/data/rest/core/ValidationErrors.java#L89

---

**Affects:** 2.6 GA (Ingalls)

2 votes, 4 watchers

**Comment by tamasbege** [comment]
Don't know about spring-data-rest, but the "normal" spring-data supports this, I am currently validating a transient object with `@Valid` in an entity.

**Comment by mjustin** [comment]
From my own explorations into a similar issue, I suspect this is due to Spring Data REST using its own [`ValidationErrors`](https://docs.spring.io/spring-data/rest/docs/current/api/org/springframework/data/rest/core/ValidationErrors.html) type to validate against, rather than the default Spring [`BeanPropertyBindingResult`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/validation/BeanPropertyBindingResult.html).  (See [`ValidatingRepositoryEventListener`](https://github.com/spring-projects/spring-data-rest/blob/master/spring-data-rest-core/src/main/java/org/springframework/data/rest/core/event/ValidatingRepositoryEventListener.java#L168)).

This `ValidationErrors` class appears to use `PersistentProperty` values on the underlying `PersistentEntity`, rather than the actual properties on the Java bean.  I haven't looked into this particular issue, but I suspect that's why it's not finding transient properties — they're not persistent properties.

**Comment by mjustin** [comment]
I haven't verified this, but as a workaround I suspect adding a listener which performs normal bean validation using a standard `BeanPropertyBindingResult` will achieve the goal of also validating transient values.

```java
/**
 * Listener which runs standard Spring bean validation before event handlers.  This does not replace the built-in
 * Spring Data REST validation, which will still be run after the event handler is invoked.
 */
@Bean
@Order(Ordered.HIGHEST_PRECEDENCE)
public ApplicationListener<RepositoryEvent> standardBeanValidationRepositoryEventListener(Validator validator) {
    return new AbstractRepositoryEventListener<Object>() {
        @Override
        protected void onBeforeCreate(Object entity) {
            validate(entity);
        }

        @Override
        protected void onBeforeSave(Object entity) {
            validate(entity);
        }

        private void validate(Object entity) {
            // Implementation based on ValidatingRepositoryEventListener & ValidationErrors

            if (entity == null) {
                return;
            }

            // Use standard BeanPropertyBindingResult rather than Spring Data REST's ValidationErrors
            Errors errors = new BeanPropertyBindingResult(entity, entity.getClass().getSimpleName());
            ValidationUtils.invokeValidator(validator, entity, errors);

            if (errors.hasErrors()) {
                throw new RepositoryConstraintViolationException(errors);
            }
        }
    };
}
```
