### ISSUE TITLE
Returning a list of projection from a custom JpaRepository method with Spring Data Rest [DATAREST-1237]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#1597]
**[Mahsum Demir](https://jira.spring.io/secure/ViewProfile.jspa?name=mahsumdemir)** opened **[DATAREST-1237](https://jira.spring.io/browse/DATAREST-1237?redirect=false)** and commented

Hi,

 

When Spring Data Rest exposes a custom JpaRepository method with the return type of List\<Projection>, GET requests to that method fails with the exception of 

```java
java.lang.IllegalArgumentException: Couldn't find PersistentEntity for type class com.sun.proxy.$Proxy117!
    at org.springframework.data.mapping.context.PersistentEntities.lambda$getRequiredPersistentEntity$2(PersistentEntities.java:78) ~[spring-data-commons-2.0.6.RELEASE.jar:2.0.6.RELEASE]
    at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_161]
    at org.springframework.data.mapping.context.PersistentEntities.getRequiredPersistentEntity(PersistentEntities.java:77) ~[spring-data-commons-2.0.6.RELEASE.jar:2.0.6.RELEASE]
    at org.springframework.data.rest.webmvc.PersistentEntityResourceAssembler.wrap(PersistentEntityResourceAssembler.java:72) ~[spring-data-rest-webmvc-3.0.6.RELEASE.jar:3.0.6.RELEASE]
    at org.springframework.data.rest.webmvc.PersistentEntityResourceAssembler.toResource(PersistentEntityResourceAssembler.java:55) ~[spring-data-rest-webmvc-3.0.6.RELEASE.jar:3.0.6.RELEASE]
    at org.springframework.data.rest.webmvc.AbstractRepositoryRestController.entitiesToResources(AbstractRepositoryRestController.java:110) ~[spring-data-rest-webmvc-3.0.6.RELEASE.jar:3.0.6.RELEASE]
    at org.springframework.data.rest.webmvc.AbstractRepositoryRestController.toResources(AbstractRepositoryRestController.java:80) ~[spring-data-rest-webmvc-3.0.6.RELEASE.jar:3.0.6.RELEASE]
    at org.springframework.data.rest.webmvc.RepositorySearchController.lambda$toResource$1(RepositorySearchController.java:209) ~[spring-data-rest-webmvc-3.0.6.RELEASE.jar:3.0.6.RELEASE]
    at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_161]
    at org.springframework.data.rest.webmvc.RepositorySearchController.toResource(RepositorySearchController.java:206) ~[spring-data-rest-webmvc-3.0.6.RELEASE.jar:3.0.6.RELEASE]
    at org.springframework.data.rest.webmvc.RepositorySearchController.executeSearch(RepositorySearchController.java:190) ~[spring-data-rest-webmvc-3.0.6.RELEASE.jar:3.0.6.RELEASE]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) ~[spring-webmvc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) ~[spring-webmvc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
```

I have created an example project at https://github.com/mahsumdemir/projection-demo.

How to reproduce error?
1. mvn spring-boot:run
2. Go to http://localhost:8080/persons/search/findByNameContains?name=i

 

Best Regards

---

10 votes, 10 watchers

**Comment by zualex-zz** [comment]
Same issue with 2.6.2

**Comment by ruthst00** [comment]
The root cause is that Spring Data REST can't resolve a `PersistentEntity` for the JDK proxy object that backs a projection interface. Spring Data REST requires the repository method to return the entity type (`Person`) — projections are then applied at the serialization layer via the `?projection=nameProjection` query parameter. Tested with `spring-boot-starter-parent:4.1.1`

With the fixes in [this PR](https://github.com/mahsumdemir/projection-demo/pull/1) you can now browse to:

`http://localhost:8080/persons/search/findByNameContains?name=i` — returns full Person entities
```
{
  "_embedded": {
    "persons": [
      {
        "_links": {
          "self": {
            "href": "http://localhost:8080/persons/1"
          },
          "person": {
            "href": "http://localhost:8080/persons/1{?projection}",
            "templated": true
          }
        },
        "age": 20,
        "id": 1,
        "name": "Dirk",
        "surname": "Deyne"
      }
    ]
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/persons/search/findByNameContains?name\u003di"
    }
  }
}
```


`http://localhost:8080/persons/search/findByNameContains?name=i&projection=nameProjection` — returns the name-only projection
```
{
  "_embedded": {
    "persons": [
      {
        "_links": {
          "self": {
            "href": "http://localhost:8080/persons/1"
          },
          "person": {
            "href": "http://localhost:8080/persons/1{?projection}",
            "templated": true
          }
        },
        "name": "Dirk"
      }
    ]
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/persons/search/findByNameContains?name\u003di\u0026projection\u003dnameProjection"
    }
  }
}
```

cc @odrotbohm
