### ISSUE TITLE
Unable to inject PersistentEntityResourceAssembler [DATAREST-1331]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-rest#1690]
**[Jefferson Lima](https://jira.spring.io/secure/ViewProfile.jspa?name=jefferson.lima)** opened **[DATAREST-1331](https://jira.spring.io/browse/DATAREST-1331?redirect=false)** and commented

According to the answer of this [question](https://stackoverflow.com/questions/31758862/enable-hal-serialization-in-spring-boot-for-custom-controller-method/31782016#31782016), I should be able to inject a `PersistentEntityResourceAssembler` in order to manually transform an entity into a `Resource`. So I wrote a controller like the following:

 

```java
@RequiredArgsConstructor
@RestController
@RequestMapping("/base")
public class BaseController {

  private final IBaseRepository baseRepository;

  @GetMapping("/{id}")
  public @ResponseBody ResponseEntity<?> list(
     @PathVariable Long id, 
     PersistentEntityResourceAssembler entityAssembler
){
    Optional<Base> base = this.baseRepository.findById(id);
    return base.map(b -> ResponseEntity.ok(entityAssembler.toResource(b)))
               .orElseGet(() -> ResponseEntity.notFound().build());
}
```

 

But then I get this error:

```java
Caused by: java.lang.IllegalArgumentException: entities is marked @NonNull but is null
 at org.springframework.data.rest.webmvc.PersistentEntityResourceAssembler.<init>(PersistentEntityResourceAssembler.java:38)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
 ... 83 more
```

 

---

**Affects:** 3.1.3 (Lovelace SR3)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
