### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.springframework.hateoas.SlicedModel

### ISSUE THREAD

**Issue by imrankhanoneassist** [spring-projects/spring-data-rest#2265]
When I add the following dependencies to my **Spring boot 3.0.6** project: 

**spring-boot-starter-parent version : 3.0.6**

**spring-cloud-dependencies version: 2022.0.2**

**JDK : 17**

Using following annotation in application class:

```
@ComponentScan(basePackages = { "xxxx", "com.spring.aop.aspects","com.spring" }, excludeFilters = @ComponentScan.Filter(type = FilterType.ASPECTJ, pattern = "xxx.*"))
@EntityScan(basePackages = "xxxx")
@EnableJpaRepositories("xxxx")
@EnableTransactionManagement
//@EnableWebMvc
@EnableDiscoveryClient
@EnableFeignClients(basePackages = {"xxxx"})
@EnableAsync
@EnableMongoRepositories("xxxxx")
@EnableCaching
@EnableScheduling
@EnableJpaAuditing
@EnableJms
@EnableRetry
@EnableConfigurationProperties(MultipartProperties.class)
```

Getting following error on service start:
 
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'slicedResourcesAssembler' defined in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]: Failed to instantiate [org.springframework.data.web.SlicedResourcesAssembler]: Factory method 'slicedResourcesAssembler' threw exception with message: org/springframework/hateoas/SlicedModel
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:493)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at com.oneassist.serviceplatform.webservice.boot.config.ServicePlatformApplication.main(ServicePlatformApplication.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.web.SlicedResourcesAssembler]: Factory method 'slicedResourcesAssembler' threw exception with message: org/springframework/hateoas/SlicedModel
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
	... 25 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/hateoas/SlicedModel
	at org.springframework.data.web.config.HateoasAwareSpringDataWebConfiguration.slicedResourcesAssembler(HateoasAwareSpringDataWebConfiguration.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 26 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.hateoas.SlicedModel
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 32 common frames omitted

```

Getting **spring-hateoas:2.0.3** dependency from **spring-boot-starter-data-rest:3.0.6** 
<img width="504" alt="image" src="https://github.com/spring-projects/spring-data-rest/assets/39180214/d38d0ccb-4d6b-489f-bb11-1d8227f8db5d">

Checked in code `SlicedModel` class is not present in hateoas:2.0.3 version.
<img width="824" alt="image" src="https://github.com/spring-projects/spring-data-rest/assets/39180214/edf843a6-f981-4aae-8fb3-ba5e4233966b">

Any idea why this is happening?

**Comment by imrankhanoneassist** [comment]
@mp911de Not added Spring Data Commons and Spring HATEOAS dependencies manually. getting all dependencies from Spring boot 3.0.6 : 
  
<img width="502" alt="image" src="https://github.com/spring-projects/spring-data-rest/assets/39180214/7abe2d1a-4d72-40e2-ba52-e3e2d6e7ff77">

**Comment by mp911de** [comment]
I don't think so. As per [Spring Data REST 4.0.5](https://repo1.maven.org/maven2/org/springframework/data/spring-data-rest-parent/4.0.5/spring-data-rest-parent-4.0.5.pom), we use Spring Data Commons 4.0.5. Please revisit your dependency version overrides.
