### ISSUE TITLE
Circular JPA entity references cause infinite recursion in LinkCollectingAssociationHandler/BasicPersistentEntity [DATAREST-396]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#773]
**[Balázs E. Pataki](https://jira.spring.io/secure/ViewProfile.jspa?name=beep)** opened **[DATAREST-396](https://jira.spring.io/browse/DATAREST-396?redirect=false)** and commented

I have an entity that has a property of the same type as the entity itself.

Something like:

```java
@Entity
public static class Location {  

  // NOTE: circular type reference
  @ManyToOne
  @JoinColumn(name="partOf")
  private Location partOf;
  …
}
```

When I create a Repository for it and try to use the exported REST service to access an instance of this entity, or any entity that references this entity will cause an infinite recursion like this:

```
at org.springframework.data.rest.webmvc.mapping.LinkCollectingAssociationHandler.doWithAssociation(LinkCollectingAssociationHandler.java:100)
at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:337)
at org.springframework.data.rest.webmvc.mapping.LinkCollectingAssociationHandler.doWithAssociation(LinkCollectingAssociationHandler.java:101)
at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:337)
at org.springframework.data.rest.webmvc.mapping.LinkCollectingAssociationHandler.doWithAssociation(LinkCollectingAssociationHandler.java:101)
at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:337)
at org.springframework.data.rest.webmvc.mapping.LinkCollectingAssociationHandler.doWithAssociation(LinkCollectingAssociationHandler.java:101)
at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:337)
at org.springframework.data.rest.webmvc.mapping.LinkCollectingAssociationHandler.doWithAssociation(LinkCollectingAssociationHandler.java:101)
at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:337)
at org.springframework.data.rest.webmvc.mapping.LinkCollectingAssociationHandler.doWithAssociation(LinkCollectingAssociationHandler.java:101)
```

It also happens when the `partOf` is not even set. I attached a simple test case, which shows this happening. Since this is not a JSON (Jackson) related bug `@JsonIgnore` cannot be used here. This seems to be some weird operation of the hypermedia link (association) generation functions.

---

**Affects:** 2.1.4 (Dijkstra SR4)

**Attachments:**
- [AssociationBug.java](https://jira.spring.io/secure/attachment/22291/AssociationBug.java) (_6.88 kB_)
- [LinkCollectingAssociationHandler.java.patch](https://jira.spring.io/secure/attachment/22764/LinkCollectingAssociationHandler.java.patch) (_1.29 kB_)

10 votes, 11 watchers

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
