### ISSUE TITLE
Update an entity with empty relationships inside [DATAREST-546]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#922]
**[Victor Mosin](https://jira.spring.io/secure/ViewProfile.jspa?name=vicmosin)** opened **[DATAREST-546](https://jira.spring.io/browse/DATAREST-546?redirect=false)** and commented

```java
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Template must not be null or empty! (through reference chain: com.data.model.UserModel["business"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1428)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:240)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2221)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:205)
	... 48 common frames omitted
Caused by: java.lang.IllegalArgumentException: Template must not be null or empty!
	at org.springframework.util.Assert.hasText(Assert.java:162)
	at org.springframework.hateoas.UriTemplate.<init>(UriTemplate.java:56)
	at org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$UriStringDeserializer.deserialize(PersistentEntityJackson2Module.java:394)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:106)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:238)
	... 52 common frames omitted
```

I understand why it happens but how can I "explain" to data rest that business CAN BE empty and it's normal behavior?

---

**Reference URL:** http://stackoverflow.com/questions/30300576/update-an-entity-with-empty-relationships-inside

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
