### ISSUE TITLE
Absolute base uri with multiple components fails [DATAREST-564]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#939]
**[Dave Handy](https://jira.spring.io/secure/ViewProfile.jspa?name=dave_h)** opened **[DATAREST-564](https://jira.spring.io/browse/DATAREST-564?redirect=false)** and commented

This test case fails, because BaseUri is trying to reverse an unmodifiable collection. A slightly broader question is why the getRepositoryLookup path logic is so different for absolute base URIs versus relative base URI.

import org.junit.Test;
import org.springframework.data.rest.webmvc.BaseUri;

public class BaseUriTest {
`@Test`
public void testbaseURi() {
BaseUri base = new BaseUri("https://example.com/services/v1/");
base.getRepositoryLookupPath("");
}
}

Caused by: java.lang.UnsupportedOperationException: null
at java.util.Collections$UnmodifiableList.set(Collections.java:1311)
at java.util.Collections.swap(Collections.java:497)
at java.util.Collections.reverse(Collections.java:378)
at org.springframework.data.rest.webmvc.BaseUri.getRepositoryLookupPath(BaseUri.java:130)

---

**Affects:** 2.2.2 (Evans SR2)

1 votes, 4 watchers

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
